"""create initial database schema

Revision ID: 176710129d5a
Revises: 
Create Date: 2026-09-29 19:24:06.448464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176710129d5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_facility_code'), 'facilities', ['facility_code'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_code', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('building_type', sa.String(length=100), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('area_sq_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_building_code'), 'buildings', ['building_code'], unique=True)
    op.create_index(op.f('ix_buildings_facility_id'), 'buildings', ['facility_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_building_id'), 'assets', ['building_id'], unique=False)
    op.create_index(op.f('ix_assets_facility_id'), 'assets', ['facility_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_code', sa.String(length=100), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_building_id'), 'devices', ['building_id'], unique=False)
    op.create_index(op.f('ix_devices_category'), 'devices', ['category'], unique=False)
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_table('air_quality_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('co2', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_quality_records_building_id'), 'air_quality_records', ['building_id'], unique=False)
    op.create_index(op.f('ix_air_quality_records_device_id'), 'air_quality_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_air_quality_records_facility_id'), 'air_quality_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_air_quality_records_recorded_at'), 'air_quality_records', ['recorded_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_building_id'), 'alerts', ['building_id'], unique=False)
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_facility_id'), 'alerts', ['facility_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('energy_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_records_building_id'), 'energy_records', ['building_id'], unique=False)
    op.create_index(op.f('ix_energy_records_device_id'), 'energy_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_energy_records_facility_id'), 'energy_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_energy_records_recorded_at'), 'energy_records', ['recorded_at'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_device_id'), 'telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_metric'), 'telemetry', ['metric'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_table('traffic_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('parking_occupancy', sa.Float(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_records_building_id'), 'traffic_records', ['building_id'], unique=False)
    op.create_index(op.f('ix_traffic_records_device_id'), 'traffic_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_traffic_records_facility_id'), 'traffic_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_traffic_records_recorded_at'), 'traffic_records', ['recorded_at'], unique=False)
    op.create_table('waste_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('waste_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_records_building_id'), 'waste_records', ['building_id'], unique=False)
    op.create_index(op.f('ix_waste_records_device_id'), 'waste_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_waste_records_facility_id'), 'waste_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_waste_records_recorded_at'), 'waste_records', ['recorded_at'], unique=False)
    op.create_table('water_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_records_building_id'), 'water_records', ['building_id'], unique=False)
    op.create_index(op.f('ix_water_records_device_id'), 'water_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_water_records_facility_id'), 'water_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_water_records_recorded_at'), 'water_records', ['recorded_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_alert_id'), 'recommendations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_recommendations_building_id'), 'recommendations', ['building_id'], unique=False)
    op.create_index(op.f('ix_recommendations_device_id'), 'recommendations', ['device_id'], unique=False)
    op.create_index(op.f('ix_recommendations_facility_id'), 'recommendations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_facility_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_device_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_building_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_alert_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_water_records_recorded_at'), table_name='water_records')
    op.drop_index(op.f('ix_water_records_facility_id'), table_name='water_records')
    op.drop_index(op.f('ix_water_records_device_id'), table_name='water_records')
    op.drop_index(op.f('ix_water_records_building_id'), table_name='water_records')
    op.drop_table('water_records')
    op.drop_index(op.f('ix_waste_records_recorded_at'), table_name='waste_records')
    op.drop_index(op.f('ix_waste_records_facility_id'), table_name='waste_records')
    op.drop_index(op.f('ix_waste_records_device_id'), table_name='waste_records')
    op.drop_index(op.f('ix_waste_records_building_id'), table_name='waste_records')
    op.drop_table('waste_records')
    op.drop_index(op.f('ix_traffic_records_recorded_at'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_facility_id'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_device_id'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_building_id'), table_name='traffic_records')
    op.drop_table('traffic_records')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_metric'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_device_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_energy_records_recorded_at'), table_name='energy_records')
    op.drop_index(op.f('ix_energy_records_facility_id'), table_name='energy_records')
    op.drop_index(op.f('ix_energy_records_device_id'), table_name='energy_records')
    op.drop_index(op.f('ix_energy_records_building_id'), table_name='energy_records')
    op.drop_table('energy_records')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_facility_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_building_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_air_quality_records_recorded_at'), table_name='air_quality_records')
    op.drop_index(op.f('ix_air_quality_records_facility_id'), table_name='air_quality_records')
    op.drop_index(op.f('ix_air_quality_records_device_id'), table_name='air_quality_records')
    op.drop_index(op.f('ix_air_quality_records_building_id'), table_name='air_quality_records')
    op.drop_table('air_quality_records')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_index(op.f('ix_devices_category'), table_name='devices')
    op.drop_index(op.f('ix_devices_building_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_assets_facility_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_building_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_buildings_facility_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_building_code'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_facilities_facility_code'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
